development:
GMAIL_USERNAME: "wurmhorst63@gmail.com"
GMAIL_PASSWORD: "emelie_24"

production:
GMAIL_USERNAME: "wurmhorst63@gmail.com"
GMAIL_PASSWORD: "emelie_24"

S3_BUCKET_NAME: "klaus50bucket"
AAWS_ACCESS_KEY_ID: "AKIAI3TYC64SQ5XDKEPQ"
AWS_SECRET_ACCESS_KEY: "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"